### PR TITLE
Allow exclusions in the .wrapRE rule

### PR DESCRIPTION
**Pull request by marcelocantos**

### CODE REVIEW

**Review by nofun97 — COMMENTED** [review]
LGTM but @anz-gordonj7 is reviewing the PR too

**Review by ghost — COMMENTED** [review]
I don't get it, shouldn't this need to exclude rules not strings? 😕 

I also really don't like the syntax

**Comment by marcelocantos** [comment]
> I don't get it, shouldn't this need to exclude rules not strings? confused

It should support excluding both rules and strings/regexps. The latter is easier, which is why I went with that for now. We can add support for rules in a follow up PR.

> I also really don't like the syntax

I'm not wedded to it. Feel free to suggest alternatives.

**Comment by marcelocantos** [comment]
I decided to merge as-is but I'm happy for someone to propose a better syntax than the current one.

**Pull request merged**
